[package]
name = "cogboy-core"
version = "0.2.0"
authors = ["BeeWarloc"]
edition = "2018"

[dependencies]
enum_primitive = "*"
num = "*"
log = "*"
serde = "1.0"
serde_derive = "1.0"
bincode = "1"
lazy_static = "1.0"
flate2 = "1.0"
